// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';

  /**
    * @ngdoc function
    * @name yoemanAngularApp.controller:AboutCtrl
    * @description
    * # AboutCtrl
    * Controller of the yoemanAngularApp
   */
  angular.module('yeomanTestApp').controller('AboutCtrl', function($scope) {
    return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
  });

}).call(this);

//# sourceMappingURL=about.map
