// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';

  /**
    * @ngdoc overview
    * @name yoemanAngularApp
    * @description
    * # yoemanAngularApp
    *
    * Main module of the application.
   */
  angular.module('yeomanTestApp', ['ngResource', 'ngRoute']).config(function($routeProvider) {
    return $routeProvider.when('/', {
      templateUrl: 'views/main.html',
      controller: 'MainCtrl'
    }).when('/about', {
      templateUrl: 'views/about.html',
      controller: 'AboutCtrl'
    }).otherwise({
      redirectTo: '/about'
    });
  });

}).call(this);

//# sourceMappingURL=app.map
